.TH "binomialvisualizer.m" 3 "Sun Jul 21 2013" "Fractal-Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binomialvisualizer.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbar\fP (\fBx\fP, \fBy\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbinomialdata\fP = importdata('binomial\&.txt')"
.br
.ti -1c
.RI "\fBx\fP = \fBbinomialdata\fP(:,1)"
.br
.ti -1c
.RI "\fBy\fP = \fBbinomialdata\fP(:,2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bar (\fBx\fP, \fBy\fP)"

.SH "Variable Documentation"
.PP 
.SS "binomialdata = importdata('binomial\&.txt')"

.PP
Definition at line 1 of file binomialvisualizer\&.m\&.
.SS "x = \fBbinomialdata\fP(:,1)"

.PP
Definition at line 2 of file binomialvisualizer\&.m\&.
.SS "y = \fBbinomialdata\fP(:,2)"

.PP
Definition at line 3 of file binomialvisualizer\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fractal-Analysis from the source code\&.
