.TH "binomialgenerator.cpp" 3 "Sun Jul 21 2013" "Fractal-Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binomialgenerator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpoint\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBassignProbabilities\fP (\fBpoint\fP *fractalArray)"
.br
.ti -1c
.RI "void \fBprintToTerminal\fP (\fBpoint\fP *arrayIn)"
.br
.ti -1c
.RI "void \fBprintToFile\fP (\fBpoint\fP *arrayIn)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBHEIGHT\fP = pow(2, 10)"
.br
.ti -1c
.RI "double \fBnormalizer\fP = 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void assignProbabilities (\fBpoint\fP *fractalArray)"

.PP
Definition at line 19 of file binomialgenerator\&.cpp\&.
.SS "int main ()"

.PP
Definition at line 75 of file binomialgenerator\&.cpp\&.
.SS "void printToFile (\fBpoint\fP *arrayIn)"

.PP
Definition at line 62 of file binomialgenerator\&.cpp\&.
.SS "void printToTerminal (\fBpoint\fP *arrayIn)"

.PP
Definition at line 52 of file binomialgenerator\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "int HEIGHT = pow(2, 10)"

.PP
Definition at line 10 of file binomialgenerator\&.cpp\&.
.SS "double normalizer = 1"

.PP
Definition at line 12 of file binomialgenerator\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fractal-Analysis from the source code\&.
