.TH "dataCorrection.h" 3 "Sun Jul 21 2013" "Fractal-Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dataCorrection.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > void \fBdataCorrection\fP (T ***&elements, int \fBHEIGHT\fP, int \fBWIDTH\fP, int \fBDEPTH\fP, bool haveZeros, T arraySum)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class T > void dataCorrection (T ***&elements, intHEIGHT, intWIDTH, intDEPTH, boolhaveZeros, TarraySum)"

.PP
Definition at line 26 of file dataCorrection\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fractal-Analysis from the source code\&.
