.TH "point" 3 "Sun Jul 21 2013" "Fractal-Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBprobability\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file binomialgenerator\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double point::probability"

.PP
Definition at line 15 of file binomialgenerator\&.cpp\&.
.SS "int point::value"

.PP
Definition at line 16 of file binomialgenerator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fractal-Analysis from the source code\&.
