.TH "regressionModule.cpp" 3 "Sun Jul 21 2013" "Fractal-Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
regressionModule.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'regressionModule\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBstdev\fP (double *arrayIn, double arrayMean, int arrayLength)"
.br
.ti -1c
.RI "double \fBcorrCoeff\fP (double *arrayX, double *arrayY, double meanX, double meanY, double stdevX, double stdevY, int length)"
.br
.ti -1c
.RI "double \fBmean\fP (double *arrayIn, int arrayLength)"
.br
.ti -1c
.RI "void \fBslope\fP (double **arrayIn, int arrayLength, double *regressionArray)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double corrCoeff (double *arrayX, double *arrayY, doublemeanX, doublemeanY, doublestdevX, doublestdevY, intlength)"

.PP
Definition at line 80 of file regressionModule\&.cpp\&.
.SS "double mean (double *arrayIn, intarrayLength)"

.PP
Definition at line 92 of file regressionModule\&.cpp\&.
.SS "void slope (double **arrayIn, intarrayLength, double *regressionArray)"
Module to run regression for boxcounting\&.
.PP
Changes a double[3] such that regressionArray[0] = slope, regressionArray[1] = R^2, and regressionArray[2] = y-int\&.
.PP
Implemented in \fBboxCounter3D\&.cpp\fP: Fractal analysis module utilizing boxcounting to determine the fractal dimension of a shape in the input text/binary file\&.
.PP
Prints to terminal:
.IP "\(bu" 2
the results at each level of analysis
.IP "\(bu" 2
the overall dimension as determined by least-squares regression
.IP "\(bu" 2
an R^2 value
.PP
.PP
\fBAuthor:\fP
.RS 4
Samuel Brenner 
.RE
.PP
\fBVersion:\fP
.RS 4
July 11, 2013
.RE
.PP
\fBAuthor:\fP
.RS 4
Samuel Brenner 
.RE
.PP
\fBVersion:\fP
.RS 4
July 11, 2013 
.RE
.PP

.PP
Definition at line 36 of file regressionModule\&.cpp\&.
.SS "double stdev (double *arrayIn, doublearrayMean, intarrayLength)"
Module to run regression for boxcounting\&.
.PP
Changes a double[3] such that regressionArray[0] = slope, regressionArray[1] = R^2, and regressionArray[2] = y-int\&.
.PP
Implemented in \fBboxCounter3D\&.cpp\fP: Fractal analysis module utilizing boxcounting to determine the fractal dimension of a shape in the input text/binary file\&.
.PP
Prints to terminal:
.IP "\(bu" 2
the results at each level of analysis
.IP "\(bu" 2
the overall dimension as determined by least-squares regression
.IP "\(bu" 2
an R^2 value
.PP
.PP
\fBAuthor:\fP
.RS 4
Samuel Brenner 
.RE
.PP
\fBVersion:\fP
.RS 4
July 11, 2013
.RE
.PP
\fBAuthor:\fP
.RS 4
Samuel Brenner 
.RE
.PP
\fBVersion:\fP
.RS 4
July 11, 2013 
.RE
.PP

.PP
Definition at line 69 of file regressionModule\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fractal-Analysis from the source code\&.
