.TH "visualization.m" 3 "Sun Jul 21 2013" "Fractal-Analysis" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visualization.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBimagesc\fP (\fBmatrix2\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmatrix2\fP = importdata('n11d2r40t20b6\&.bin_interpolated\&.txt')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "imagesc (\fBmatrix2\fP)"

.SH "Variable Documentation"
.PP 
.SS "matrix2 = importdata('n11d2r40t20b6\&.bin_interpolated\&.txt')"

.PP
Definition at line 3 of file visualization\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fractal-Analysis from the source code\&.
